version: "3"
services:
  jupyterlab:
    # docker run --rm -i -v $PWD:/tf/notebooks -p 8888:8888 openjny/tensorflow:latest jupyter lab --allow-root --no-browser
    # build: .
    image: openjny/tensorflow:latest
    # tty: true
    expose:
      - "8888"
    ports:
      - "8888:8888"
    volumes:
      - "./:/tf/notebooks"
    command: jupyter lab --allow-root --ip=0.0.0.0 --no-browser --NotebookApp.token=''
